apiVersion: v1
kind: RoleBinding
metadata:
  name: view
roleRef:
  name: view
subjects:
- kind: ServiceAccount
  name: default
  namespace: hello-istio
userNames:
- system:serviceaccount:hello-istio:default